name: config-check

on:
  push:
  pull_request:

jobs:
  lua-syntax:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: rhysd/action-setup-vim@v1
        with:
          version: v0.12.0
          neovim: true
      - name: Check Lua syntax
        run: nvim --headless -u NONE -i NONE -l scripts/check.lua
